armv7-m irq: avoid uninitialized compiler warning/error
arm-none-eabi-gcc 12.2.0 gives the following warning:
error: 'primask' is used uninitialized

We use Werror and the file is indirectly included in different
places. I suggest muting the warning and hence error since the
initialization is not needed.

This is the only problem I encountered so far when upgrading the compiler.